

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=dhruvajb
      - DB_PASSWORD=password
      - DB_NAME=loan_evaluator_db
    volumes:
      - ./backend/pdfData:/app/pdfData
      - ./backend/data_processing:/app/data_processing
    depends_on:
      - db

  frontend:
    build: ./frontend/my-loan-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: dhruvajb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_evaluator_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432" # Optional for local access

volumes:
  db-data:
